version: "2"

services:
  keycloack:
    image: docker.io/jboss/keycloak:16.1.1
    ports:
      - ${KEYCLOAK_LOCAL_PORT}:8080
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_IMPORT=${KEYCLOAK_IMPORT_PATH}${KEYCLOAK_IMPORT}
    volumes:
      - ./keycloak/imports:${KEYCLOAK_IMPORT_PATH}
      - ./keycloak/themes/poc-theme:/opt/jboss/keycloak/themes/poc-theme
      - ./keycloak/data:/opt/jboss/keycloak/standalone/data
    command:
      - "-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled"


